# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'module_wtyczka_projekt2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczka_projekt2DialogBase(object):
    def setupUi(self, wtyczka_projekt2DialogBase):
        wtyczka_projekt2DialogBase.setObjectName("wtyczka_projekt2DialogBase")
        wtyczka_projekt2DialogBase.resize(660, 510)
        self.button_box = QtWidgets.QDialogButtonBox(wtyczka_projekt2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(60, 470, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.mMapLayerComboBox = QgsMapLayerComboBox(wtyczka_projekt2DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(380, 40, 191, 51))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.label_layer_choose = QtWidgets.QLabel(wtyczka_projekt2DialogBase)
        self.label_layer_choose.setGeometry(QtCore.QRect(100, 30, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_layer_choose.setFont(font)
        self.label_layer_choose.setObjectName("label_layer_choose")
        self.pushButton_dh_calculate = QtWidgets.QPushButton(wtyczka_projekt2DialogBase)
        self.pushButton_dh_calculate.setGeometry(QtCore.QRect(100, 110, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_dh_calculate.setFont(font)
        self.pushButton_dh_calculate.setObjectName("pushButton_dh_calculate")
        self.label_dh_result2 = QtWidgets.QLabel(wtyczka_projekt2DialogBase)
        self.label_dh_result2.setGeometry(QtCore.QRect(110, 200, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_dh_result2.setFont(font)
        self.label_dh_result2.setObjectName("label_dh_result2")
        self.label_dh_result = QtWidgets.QLabel(wtyczka_projekt2DialogBase)
        self.label_dh_result.setGeometry(QtCore.QRect(400, 200, 171, 51))
        self.label_dh_result.setText("")
        self.label_dh_result.setObjectName("label_dh_result")

        self.retranslateUi(wtyczka_projekt2DialogBase)
        self.button_box.accepted.connect(wtyczka_projekt2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(wtyczka_projekt2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyczka_projekt2DialogBase)

    def retranslateUi(self, wtyczka_projekt2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczka_projekt2DialogBase.setWindowTitle(_translate("wtyczka_projekt2DialogBase", "wtyczka_projekt2"))
        self.label_layer_choose.setText(_translate("wtyczka_projekt2DialogBase", " Wybierz warstwe:"))
        self.pushButton_dh_calculate.setText(_translate("wtyczka_projekt2DialogBase", "Oblicz dh"))
        self.label_dh_result2.setText(_translate("wtyczka_projekt2DialogBase", "Wynik dh:"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wtyczka_projekt2DialogBase = QtWidgets.QDialog()
    ui = Ui_wtyczka_projekt2DialogBase()
    ui.setupUi(wtyczka_projekt2DialogBase)
    wtyczka_projekt2DialogBase.show()
    sys.exit(app.exec_())
